name: Build and Test CareFinder Agent App (Native)

on:
  push:
    branches:
      - "main" # Best to run this only on your main branch, or specific release branches
    # This workflow will only run on pushes where files in these paths have changed.
    paths:
      - 'Agent_App/**'
      - '.github/workflows/agent-app-native.yaml'

  pull_request:
    branches:
      - "main"
    # This workflow will only run on pull requests where files in these paths have changed.
    paths:
      - 'Agent_App/**'
      - '.github/workflows/agent-app-native.yaml'

jobs:
  Build-Android-Native:
    # This condition checks that the job is running in your main repository,
    # not in a fork. This prevents PRs from outside contributors from
    # running on your personal machine.
    if: github.repository == 'DarkDeciders/CareFinder'
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./Agent_App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with dependency caching
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: Agent_App/package-lock.json

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install JavaScript dependencies
        run: npm ci

      - name: Grant execute permission to gradlew
        run: chmod +x android/gradlew

      - name: Build Android Release APK
        run: cd android && ./gradlew assembleRelease
        env:
          NODE_ENV: production

      # --- NEW STEP TO UPLOAD THE APK ---
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: carefinder-agent-app-apk
          path: Agent_App/android/app/build/outputs/apk/release/app-release.apk