name: Build and Test CareFinder Frontend

on:
  # Run on pushes to any branch
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/build-and-test.yml'

  # Run on pull requests targeting any branch, but only when frontend files or this workflow change
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/build-and-test.yml'

jobs:
  Build-Test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step caches npm dependencies and sets up Node.js
      - name: Set up Node.js with dependency caching
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # This step specifically caches the Next.js build output
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: ./frontend/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('frontend/**/*.js', 'frontend/**/*.jsx', 'frontend/**/*.ts', 'frontend/**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Build Command
        run: npm run build
        env:
          # Add any environment variables needed for your CareFinder project
          # For example, if you have API keys or other secrets:
          # NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production
